version: "3.8"


services:
  frontend:
    build:
      context: ./frontend/Dockerfile 
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:8000

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend/Dockerfile
    environment:
      - DATABASE_URL=postgres://app:changethis123@db:5432/app
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["sh", "-c", "poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"]
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
