version: "3.8"


services:
  frontend:
    build:
      context: ./frontend/Dockerfile 
    ports:
      - "5173:5173"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
        ADMINER_DEFAULT_SEVERAL: db

  backend:
    build:
      context: ./backend/Dockerfile
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

      
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
