version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8081:8000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://app:changethis123@db:5432/app
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["sh", "-c", "poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"]

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - backend_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8090:81"
    environment:
      DB_DATABASE: proxy
      DB_USER: app
      DB_PASSWORD: changethis123
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./proxy_data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx-proxy-manager:/app/data
    restart: always
    networks:
      - backend_network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
