version: "3.8"

services:
  frontend:
    build: ./frontend/Dockerfile
    ports:
      - "80:80" 
    volumes:
      - ./frontend:/app:ro  

  backend:
    build: ./backend
    ports:
      - "8000:8000"  
    environment:
      - DATABASE_URL=postgresql://techynurse:admin123@db:5432/HNG 
      - db  

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin123 
    volumes:
      - postgres-data:/var/lib/postgresql/data  

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Map container port 80 to host port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  
    depends_on:
      - frontend
      - backend

volumes:
  postgres-data: {}  
