version: "3.8"


services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
        ADMINER_DEFAULT_SEVERAL: db

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '8090:81'
      - '80:80'
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
      - ./conf_files:/conf_files
      - ./entrypoint.sh:/entrypoint.sh
    command: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]

  backend:
    build:
      context: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db


  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./letsencrypt:/etc/letsencrypt
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  db_data:
